### ISSUE TITLE
How to actually use this plugin?

### ISSUE THREAD

**Issue by Kostronor** [JetBrains/teamcity-amazon-ecs-plugin#7]
From what I see this plugin allows to start tasks. But this does not scale the underlying containers. So that means that we have to always keep containers running even if tasks are not needed.

Would it be possible to have the plugin just start a container with one task (the build agent) and have it running till we want it to stop? What do I have to do to achieve that?

**Comment by ekoshkin** [comment]
Hi, @Kostronor. 
Plugin actually starts tasks - set of connected containers with build agent inside. And stop those tasks if TeamCity doesn't need particular build agent (and task) anymore.
Maybe you are talking about scaling group of container instances (EC2 instances) connected to ECS cluster. If so - you are right, plugin does not manage them, And I think it should not.
As far as I know - scaling of underlaying EC2 resources ususally performed by autoscalling group which should be configured in advanced by cluster administrator.
Do this make sence for you? Please correct me if I am wrong.

**Comment by Kostronor** [comment]
How would I go about setting up my EC2 autoscaling to always start one EC2 container per task (and therefor buildagent needed) and stop these containers down to 0 once no builds are queued?

**Comment by ekoshkin** [comment]
You can define how many containers you want to run concurrently on one EC2 instance by configuring contaner CPU and / or memory requiremenets.
Containers (tasks) will be shut down by TeamCity server - that is how TeamCity cloud agents feature works. 
As for EC2 instances - it is a autoscaling policy to scale (up and down) based on memory usage.

We plan to share this configuration in blog post when first plugin release will be published. 
Blogpost will describe our own usage of this plugin to run build agents connected to http://teamcity.jetbrains.com
It will also provide an example how to use EFS (elastic file system) to provide elastic storage for running agents.

**Comment by Kostronor** [comment]
Looking forward to the blog post then :)
